# Services that help in debugging
# How to Run -> docker-compose up -f docker-compose.yml -f docker-compose-debug.yml up -d

version: "3"

services:
  
  akhq:
    image: tchiotludo/akhq
    ports:
     - "18080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          security:
            basic-auth:
              - username: admin
                password: d49745a74edfd20705ccaa277209db554b6b0d78c20780a4facf87e88aee78c0
                groups: 
                  - admin
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                - name: "connect"
                  url: "http://connect:8083"
